import { readFileSync, realpathSync } from 'node:fs';
import { relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { fetchProfile as githubFetchProfile, GitHubError, type FetchOptions } from '../core/github.ts';
import { compact } from '../core/format.ts';
import { getTheme } from '../core/themes.ts';
import type { ProfileData } from '../core/types.ts';
import { readmeMarkup, renderCards, type RenderedFile } from '../render.ts';
import { ConfigError, parseConfigJson, resolveConfig, type ResolvedConfig } from './config.ts';
import {
  actionsLogger,
  actionsOutputs,
  displayPath,
  formatBytes,
  loadConfigText,
  readInputs,
  writeFiles,
  type Env,
  type Logger,
  type Outputs,
} from './io.ts';
import { publishToBranch, PublishError, rawBaseUrl, type PublishResult } from './publish.ts';
import { missingMarkersHelp, START_MARKER, END_MARKER, updateReadme, wrapWithMarkers, type ReadmeUpdateResult } from './readme.ts';

/**
 * GitHub Action entry point: inputs -> fetch -> render -> write -> publish ->
 * README update -> step summary + outputs.
 */

export const PROJECT_URL = 'https://github.com/chethandvg/profilescape';
export const SNIPPET_FILE = 'README-snippet.md';

export interface RunDeps {
  env?: Env;
  log?: Logger;
  outputs?: Outputs;
  /** Used for publishing and the README update. */
  fetchImpl?: typeof fetch;
  /** Swappable data source (tests use fixtures). */
  fetchProfile?: (o: FetchOptions) => Promise<ProfileData>;
  now?: Date;
  cwd?: string;
  /** Base delay for REST retries (tests pass 0). */
  retryDelayMs?: number;
}

/** Contents of README-snippet.md: the markup wrapped in update markers. */
export function snippetDocument(markup: string): string {
  return `${wrapWithMarkers(markup)}\n`;
}

/** Landing page shown when someone opens the output branch on GitHub. */
export function branchReadme(login: string, files: RenderedFile[], markup: string): string {
  return [
    '# Profilescape cards',
    '',
    `Generated by [Profilescape](${PROJECT_URL}) for [@${login}](https://github.com/${login}).`,
    'This branch is rewritten by every run as a single commit with no history, so please do not edit it by hand.',
    '',
    '## Preview',
    '',
    readmeMarkup(files, '.'),
    '',
    '## Use in a README',
    '',
    `Paste this where the cards should appear. Keep the markers if you want the \`readme\` input to keep it up to date.`,
    '',
    '```html',
    wrapWithMarkers(markup),
    '```',
    '',
  ].join('\n');
}

export function friendlyError(err: unknown): string {
  if (err instanceof ConfigError || err instanceof PublishError) return err.message;
  if (err instanceof GitHubError) {
    if (err.status === 401) {
      return (
        `${err.message}\nThe "token" input is used to read your profile. If it comes from a secret such as PROFILESCAPE_TOKEN, ` +
        'the personal access token has probably expired or been revoked: create a new one and update the secret, ' +
        'or remove the "token" input to fall back to the workflow token (public data only).'
      );
    }
    if (err.status === 404) return `${err.message}\nCheck the "username" input (it defaults to the repository owner).`;
    if (err.status === 403 || err.status === 429) {
      return `${err.message}\nIf this is a rate limit, the next scheduled run will succeed; otherwise check that the "token" input can read the profile.`;
    }
    return err.message;
  }
  const e = err as Error;
  return `Unexpected error: ${e?.stack ?? String(err)}\nPlease report this at ${PROJECT_URL}/issues`;
}

/** True when the triggering event says the repository is private (raw URLs then need auth). */
export function repositoryIsPrivate(env: Env): boolean {
  if (!env.GITHUB_EVENT_PATH) return false;
  try {
    const event = JSON.parse(readFileSync(env.GITHUB_EVENT_PATH, 'utf8')) as { repository?: { private?: boolean } };
    return event.repository?.private === true;
  } catch {
    return false;
  }
}

function graphqlUrl(env: Env): string | undefined {
  if (env.GITHUB_GRAPHQL_URL) return env.GITHUB_GRAPHQL_URL;
  const api = env.GITHUB_API_URL?.replace(/\/+$/, '');
  if (!api || api === 'https://api.github.com') return undefined;
  // GHES: https://host/api/v3 -> https://host/api/graphql
  return api.replace(/\/v3$/, '') + '/graphql';
}

function describeConfig(r: ResolvedConfig): string[] {
  const { config: c, settings: s, sources } = r;
  const src = (k: keyof ResolvedConfig['sources']) => (sources[k] === 'default' ? '' : `  (${sources[k]})`);
  const list = (v: string[]) => (v.length ? v.join(', ') : '-');
  return [
    `username         ${c.username}`,
    `cards            ${c.cards.join(', ')}${src('cards')}`,
    `theme            ${c.theme}${src('theme')}`,
    `modes            ${c.modes.join(', ')}${src('modes')}`,
    `animate          ${c.animate}${src('animate')}`,
    `history          ${s.history}${src('history')}`,
    `include_private  ${c.includePrivate}${src('includePrivate')}`,
    `hide_languages   ${list(c.hideLanguages)}${src('hideLanguages')}`,
    `exclude_repos    ${list(c.excludeRepos)}${src('excludeRepos')}`,
    `repos            ${list(c.repos)}${src('repos')}`,
    `output_dir       ${s.outputDir}`,
    `publish          ${s.publish === 'branch' ? `branch "${s.branch}"` : 'none'}`,
    `readme           ${s.readme || '-'}`,
  ];
}

function summaryMarkdown(args: {
  login: string;
  theme: string;
  files: RenderedFile[];
  markup: string;
  displayed: string[];
  publish?: PublishResult;
  branch: string;
  readme?: ReadmeUpdateResult;
}): string {
  const { files, publish } = args;
  const images = new Set(files.map((f) => f.name)).size;
  const where = publish
    ? ` and published them to [\`${args.branch}\`](${publish.branchUrl}) (${publish.status === 'unchanged' ? 'no changes since the last run' : publish.status})`
    : '';
  const readmeLine =
    args.readme?.status === 'updated'
      ? `\n\nUpdated \`${args.readme.path}\` between the Profilescape markers.`
      : args.readme?.status === 'unchanged'
        ? `\n\n\`${args.readme.path}\` is already up to date.`
        : args.readme
          ? `\n\n> [!WARNING]\n> \`${args.readme.path}\` has no \`${START_MARKER}\` / \`${END_MARKER}\` markers, so it was not changed.`
          : '';
  const table = files.map((f, i) => `| \`${args.displayed[i] ?? f.path}\` | ${f.card} | ${f.mode} | ${formatBytes(new TextEncoder().encode(f.svg).length)} |`);
  return [
    '## Profilescape',
    '',
    `Rendered **${images}** ${images === 1 ? 'image' : 'images'} (${files.length} files) for [@${args.login}](https://github.com/${args.login}) with the **${getTheme(args.theme).label}** theme${where}.${readmeLine}`,
    '',
    ...(publish ? [args.markup, ''] : []),
    '<details><summary>README snippet</summary>',
    '',
    '```html',
    wrapWithMarkers(args.markup),
    '```',
    '',
    '</details>',
    '',
    '<details><summary>Files</summary>',
    '',
    '| File | Card | Mode | Size |',
    '| --- | --- | --- | --- |',
    ...table,
    '',
    '</details>',
    '',
  ].join('\n');
}

export async function run(deps: RunDeps = {}): Promise<number> {
  const env = deps.env ?? process.env;
  const baseLog = deps.log ?? actionsLogger(undefined, env);
  // Track the open group so a failure is never hidden inside a collapsed group.
  let groupOpen = false;
  const log: Logger = {
    ...baseLog,
    group: (name) => {
      if (groupOpen) baseLog.endGroup();
      baseLog.group(name);
      groupOpen = true;
    },
    endGroup: () => {
      if (groupOpen) baseLog.endGroup();
      groupOpen = false;
    },
  };
  const outputs = deps.outputs ?? actionsOutputs(env, log);
  const workspace = resolve(env.GITHUB_WORKSPACE || deps.cwd || process.cwd());
  const fetchProfile = deps.fetchProfile ?? githubFetchProfile;
  const now = deps.now ?? new Date();

  try {
    const inputs = readInputs(env);
    for (const secret of [inputs.token, inputs.github_token]) if (secret) log.mask(secret);

    const loaded = loadConfigText(inputs.config ?? '', workspace);
    const json = loaded ? parseConfigJson(loaded.text, loaded.source) : undefined;
    const resolved = resolveConfig(inputs, json, { defaultUsername: env.GITHUB_REPOSITORY_OWNER, ignoreDefaultInputs: true });
    const { config, settings } = resolved;
    for (const w of resolved.warnings) log.warning(w, { title: 'Profilescape config' });

    log.group('Configuration');
    if (loaded) log.info(`config           ${loaded.source}`);
    for (const line of describeConfig(resolved)) log.info(line);
    log.endGroup();

    if (!settings.token) {
      throw new ConfigError('No token: the "token" input is empty. It defaults to ${{ github.token }}; if you overrode it, check that the secret exists.');
    }
    const repository = env.GITHUB_REPOSITORY ?? '';
    if ((settings.publish === 'branch' || settings.readme) && !/^[^/\s]+\/[^/\s]+$/.test(repository)) {
      throw new ConfigError(
        'GITHUB_REPOSITORY is not set, so there is nowhere to publish. Run inside GitHub Actions, or set "publish: none" (and no "readme") to only write files.',
      );
    }

    // 1. Data
    log.group(`Fetching GitHub data for @${config.username}`);
    if (config.includePrivate && settings.token.startsWith('ghs_')) {
      log.info(
        'Using the workflow token, which sees public activity only. To include private contributions, pass a personal access token as the "token" input.',
      );
    }
    const data = await fetchProfile({
      token: settings.token,
      login: config.username,
      history: settings.history,
      includePrivate: config.includePrivate,
      hideLanguages: config.hideLanguages,
      excludeRepos: config.excludeRepos,
      extraRepos: config.repos,
      now,
      apiUrl: graphqlUrl(env),
      log: (m) => log.info(m),
    });
    const totalAllTime = data.calendar.reduce((s, d) => s + d.count, 0);
    log.info(
      `@${data.login}: ${compact(data.year.contributions)} contributions in the last year` +
        (settings.history === 'full' ? `, ${compact(totalAllTime)} all-time` : '') +
        `, ${data.repos.length} repositories, ${data.languages.length} languages.`,
    );
    log.endGroup();

    // 2. Render
    log.group('Rendering cards');
    const files = renderCards({
      data,
      cards: config.cards,
      theme: config.theme,
      colors: config.colors,
      darkColors: config.darkColors,
      lightColors: config.lightColors,
      modes: config.modes,
      options: config.options,
      animate: config.animate,
      now,
    });
    if (!files.length) throw new ConfigError('The selected cards produced no images.');
    const width = Math.max(...files.map((f) => f.path.length)) + 2;
    for (const f of files) log.info(`${f.path.padEnd(width)}${formatBytes(new TextEncoder().encode(f.svg).length).padStart(9)}`);
    log.endGroup();

    // 3. Write
    const outDir = resolve(workspace, settings.outputDir);
    const relOut = relative(workspace, outDir).split('\\').join('/');
    const baseUrl =
      settings.publish === 'branch' ? rawBaseUrl(repository, settings.branch, env.GITHUB_SERVER_URL) : relOut && !relOut.startsWith('..') ? relOut : '.';
    const markup = readmeMarkup(files, baseUrl);
    const snippet = snippetDocument(markup);
    const written = writeFiles(outDir, [...files.map((f) => ({ path: f.path, content: f.svg })), { path: SNIPPET_FILE, content: snippet }]);
    const displayed = written.map((p) => displayPath(p, workspace));
    log.info(`Wrote ${written.length} files to ${displayPath(outDir, workspace) || '.'}`);

    // 4. Publish
    let published: PublishResult | undefined;
    if (settings.publish === 'branch') {
      log.group(`Publishing to ${repository}@${settings.branch}`);
      published = await publishToBranch({
        token: settings.githubToken,
        repository,
        branch: settings.branch,
        message: settings.commitMessage,
        files: [
          ...files.map((f) => ({ path: f.path, content: f.svg })),
          { path: SNIPPET_FILE, content: snippet },
          { path: 'README.md', content: branchReadme(data.login, files, markup) },
        ],
        apiUrl: env.GITHUB_API_URL,
        serverUrl: env.GITHUB_SERVER_URL,
        fetchImpl: deps.fetchImpl,
        retryDelayMs: deps.retryDelayMs,
        log: (m) => log.info(m),
      });
      log.info(`Cards are served from ${published.baseUrl}`);
      if (repositoryIsPrivate(env)) {
        log.warning(
          `${repository} is private, so visitors cannot load images from ${published.baseUrl}. Run Profilescape in a public repository (such as your ${env.GITHUB_REPOSITORY_OWNER ?? 'username'}/${env.GITHUB_REPOSITORY_OWNER ?? 'username'} profile repository).`,
          { title: 'Images will not be visible' },
        );
      }
      log.endGroup();
    }

    // 5. README
    let readme: ReadmeUpdateResult | undefined;
    if (settings.readme) {
      log.group(`Updating ${settings.readme}`);
      readme = await updateReadme({
        token: settings.githubToken,
        repository,
        path: settings.readme,
        markup,
        message: settings.commitMessage,
        apiUrl: env.GITHUB_API_URL,
        fetchImpl: deps.fetchImpl,
        retryDelayMs: deps.retryDelayMs,
        log: (m) => log.info(m),
      });
      if (readme.status === 'unchanged') log.info(`${readme.path} is already up to date.`);
      else if (readme.status === 'missing-markers') log.warning(missingMarkersHelp(readme.path), { title: 'README not updated' });
      else if (readme.status === 'misordered-markers') {
        log.warning(`${readme.path}: "${END_MARKER}" must come after "${START_MARKER}". The README was not changed.`, { title: 'README not updated' });
      }
      log.endGroup();
    }

    // 6. Summary + outputs
    outputs.summary(summaryMarkdown({ login: data.login, theme: config.theme, files, markup, displayed, publish: published, branch: settings.branch, readme }));
    outputs.set('files', JSON.stringify(displayed));
    outputs.set('markup', markup);
    outputs.set('base_url', baseUrl);
    if (settings.publish === 'none' && !settings.readme) {
      log.info(`Done. Commit ${displayPath(outDir, workspace) || '.'} to your repository, or paste ${SNIPPET_FILE} into your README.`);
    } else {
      log.info('Done.');
    }
    return 0;
  } catch (err) {
    log.endGroup();
    log.error(friendlyError(err), { title: 'Profilescape failed' });
    return 1;
  }
}

function isEntryPoint(): boolean {
  const entry = process.argv[1];
  if (!entry) return false;
  try {
    return realpathSync(entry) === realpathSync(fileURLToPath(import.meta.url));
  } catch {
    return false;
  }
}

if (isEntryPoint()) {
  process.exitCode = await run();
}
