import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import * as simpleIcons from 'simple-icons';

/**
 * Generates src/cards/icons.generated.ts from the installed `simple-icons`
 * package (CC0-1.0). Only a curated set of popular developer technologies and
 * social platforms is embedded so the browser bundle stays small; anything
 * else falls back to a monogram tile in src/cards/icons.ts.
 *
 *   node scripts/gen-icons.ts
 *
 * Slugs that a future simple-icons release removes are skipped with a warning
 * (icons.ts then serves a monogram for them), so regenerating never breaks.
 */

const CURATED: Record<string, string[]> = {
  language: [
    'typescript', 'javascript', 'python', 'go', 'rust', 'c', 'cplusplus', 'kotlin', 'swift', 'ruby', 'php',
    'scala', 'elixir', 'erlang', 'haskell', 'clojure', 'dart', 'lua', 'r', 'julia', 'zig', 'ocaml', 'fsharp',
    'solidity', 'webassembly', 'html5', 'css', 'sass', 'markdown', 'mdx', 'gnubash', 'openjdk', 'latex',
  ],
  framework: [
    'react', 'nextdotjs', 'vuedotjs', 'nuxt', 'svelte', 'angular', 'solid', 'astro', 'remix', 'vite', 'webpack',
    'esbuild', 'tailwindcss', 'bootstrap', 'shadcnui', 'redux', 'threedotjs', 'd3', 'jquery', 'htmx', 'express',
    'nestjs', 'fastify', 'hono', 'django', 'flask', 'fastapi', 'rubyonrails', 'laravel', 'spring', 'springboot',
    'dotnet', 'blazor', 'graphql', 'trpc', 'prisma', 'drizzle', 'flutter', 'electron', 'tauri', 'expo',
  ],
  runtime: ['nodedotjs', 'deno', 'bun', 'nuget', 'npm', 'pnpm', 'yarn'],
  data: [
    'postgresql', 'mysql', 'mariadb', 'sqlite', 'mongodb', 'redis', 'supabase', 'firebase', 'neo4j', 'duckdb',
    'elasticsearch', 'apachekafka', 'rabbitmq', 'databricks', 'apachespark', 'snowflake', 'apacheairflow',
  ],
  ai: [
    'pytorch', 'tensorflow', 'scikitlearn', 'numpy', 'pandas', 'jupyter', 'opencv', 'huggingface', 'anthropic',
    'claude', 'langchain', 'ollama', 'githubcopilot',
  ],
  cloud: ['googlecloud', 'cloudflare', 'vercel', 'netlify', 'digitalocean', 'flydotio'],
  devops: [
    'docker', 'kubernetes', 'helm', 'terraform', 'ansible', 'nginx', 'githubactions', 'gitlab', 'jenkins', 'argo',
    'grafana', 'prometheus', 'opentelemetry', 'sentry',
  ],
  tool: [
    'git', 'github', 'linux', 'ubuntu', 'archlinux', 'nixos', 'apple', 'android', 'ios', 'raspberrypi', 'arduino',
    'vim', 'neovim', 'gnuemacs', 'jetbrains', 'intellijidea', 'pycharm', 'rider', 'xcode', 'androidstudio',
    'cursor', 'postman', 'figma', 'notion', 'jira', 'vitest', 'jest', 'cypress', 'storybook', 'eslint', 'prettier',
    'unity', 'godotengine', 'blender',
  ],
  social: [
    'x', 'mastodon', 'bluesky', 'threads', 'youtube', 'twitch', 'reddit', 'devdotto', 'hashnode', 'medium',
    'substack', 'stackoverflow', 'discord', 'telegram', 'instagram', 'gmail', 'rss', 'githubsponsors', 'kofi',
    'buymeacoffee', 'patreon', 'leetcode', 'kaggle', 'dribbble', 'behance', 'codeberg', 'orcid', 'googlescholar',
  ],
};

interface SimpleIcon {
  slug: string;
  title: string;
  hex: string;
  path: string;
}

const root = join(import.meta.dirname, '..');
const version = (JSON.parse(readFileSync(join(root, 'node_modules/simple-icons/package.json'), 'utf8')) as { version: string })
  .version;
const bySlug = new Map<string, SimpleIcon>();
for (const value of Object.values(simpleIcons) as unknown[]) {
  const icon = value as Partial<SimpleIcon> | null;
  if (icon && typeof icon.slug === 'string' && typeof icon.path === 'string') bySlug.set(icon.slug, icon as SimpleIcon);
}

const lines: string[] = [];
const seen = new Set<string>();
const missing: string[] = [];
for (const [category, slugs] of Object.entries(CURATED)) {
  for (const slug of slugs) {
    if (seen.has(slug)) continue;
    seen.add(slug);
    const icon = bySlug.get(slug);
    if (!icon) {
      missing.push(slug);
      continue;
    }
    const entry = `{ title: ${JSON.stringify(icon.title)}, hex: ${JSON.stringify(icon.hex.toUpperCase())}, category: ${JSON.stringify(category)}, path: ${JSON.stringify(icon.path)} }`;
    lines.push(`  ${JSON.stringify(slug)}: ${entry},`);
  }
}

const out = `// Generated by scripts/gen-icons.ts from simple-icons v${version}. Do not edit by hand; run \`npm run gen:icons\`.
//
// Icon paths come from Simple Icons (https://simpleicons.org), released under CC0-1.0.
// Brand names and logos are trademarks of their respective owners. Their use here
// does not imply endorsement; follow each brand's guidelines when displaying them.

export type IconCategory = ${Object.keys(CURATED).map((c) => JSON.stringify(c)).join(' | ')};

export interface GeneratedIcon {
  title: string;
  /** Brand colour without "#". */
  hex: string;
  category: IconCategory;
  /** SVG path data on a 24×24 canvas. */
  path: string;
}

export const SIMPLE_ICONS_VERSION = ${JSON.stringify(version)};

export const ICONS: Readonly<Record<string, GeneratedIcon>> = {
${lines.join('\n')}
};
`;

const target = join(root, 'src/cards/icons.generated.ts');
writeFileSync(target, out);
console.log(`wrote ${lines.length} icons to ${target} (${(out.length / 1024).toFixed(1)} KB)`);
if (missing.length) console.warn(`skipped (not in simple-icons v${version}): ${missing.join(', ')}`);
